### PR TITLE
Fix Xcode 13 build error

### PR DESCRIPTION
**Pull request by SergeyKovalenko**
Bump PathKit to 1.0.1

### CODE REVIEW

**Comment by fgauchet** [comment]
👋  @g-amichnia any chance we can get a new version of CLI with the fix?

**Comment by g-amichnia** [comment]
Working on that

**Comment by fgauchet** [comment]
Hey @g-amichnia do you have an ETA on getting a new version?

**Comment by pschneider** [comment]
@fgauchet Assuming it is still blocked by #16 due to the used Sourcery version being incompatible

**Pull request merged**
